# This builds the documentation using sphinx and commits it to the main

name: "Pull Request Docs Check"
on: 
  push:
    branches: 'main'


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - run: mkdir -p docs/_build/html/
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/