# This builds the documentation using sphinx and commits it to the main

name: "Push to Main Docs Check"
on: 
  push:
    branches: 'main'


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"